-- Creating tables for NBA Stats

CREATE TABLE game_statistics(
	game_index INT NOT NULL,
	date DATE NOT NULL,
	away_team VARCHAR NOT NULL,
	home_team VARCHAR NOT NULL,
	home_team_roster VARCHAR NOT NULL,
	away_team_roster VARCHAR NOT NULL,
	outcome VARCHAR NOT NULL
	
);

CREATE TABLE player_statistics(
	home_team_PER FLOAT NOT NULL,
	home_team_win FLOAT NOT NULL,
	away_team_PER FLOAT NOT NULL,
	away_team_win FLOAT NOT NULL,
	home_team_roster VARCHAR NOT NULL,
	away_team_roster VARCHAR NOT NULL
);

CREATE TABLE game_features(
	PTS BIGINT NOT NULL,
	FGA BIGINT NOT NULL,
	FG3A BIGINT NOT NULL,
	FTA BIGINT NOT NULL,
	OREB BIGINT NOT NULL,
	DREB BIGINT NOT NULL,
	AST BIGINT NOT NULL,
	STL DOUBLE PRECISION NOT NULL,
	BLK BIGINT NOT NULL,
	TOV BIGINT NOT NULL,
	PF BIGINT NOT NULL
);

CREATE TABLE games(
	SEASON_ID BIGINT NOT NULL,
	TEAM_ID BIGINT NOT NULL,
	TEAM_ABBREVIATION VARCHAR NOT NULL,
	TEAM_NAME VARCHAR NOT NULL,
	GAME_ID INT NOT NULL,
	GAME_DATE DATE NOT NULL,
	MATCHUP VARCHAR NOT NULL,
	WL VARCHAR NOT NULL,
	MIN INT NOT NULL,
	PTS INT NOT NULL,
	FGM INT NOT NULL,
	FGA INT NOT NULL,
	FG_PCT DOUBLE PRECISION NULL,
	FG3M INT NOT NULL,
	FG3A INT NOT NULL,
	FG3_PCT DOUBLE PRECISION NULL,
	FTM INT NOT NULL,
	FTA INT NOT NULL,
	FT_PCT DOUBLE PRECISION NOT NULL,
	OREB INT NOT NULL,
	DREB INT NOT NULL,
	REB INT NOT NULL,
	AST INT NOT NULL,
	STL DOUBLE PRECISION NOT NULL,
	BLK INT NOT NULL,
	TOV INT NOT NULL,
	PF INT NOT NULL,
	PLUS_MINUS DOUBLE PRECISION NOT NULL
);